# Training Hyperparameters
INPUT_SIZE = (15, 15)
INPUT_CHANNELS = 11
OUTPUT_CHANNELS = 1
LEARNING_RATE = 0.001
BATCH_SIZE = 512
NUM_EPOCHS = 20
MIN_EPOCHS = 1
MAX_EPOCHS = 30


# Dataset
# DATA_DIR
NUM_WORKERS = 12

# Compute related
ACCELERATOR = "gpu"
DEVICES = [0]
PRECISION = 32
